# Generated by Django 4.0.4 on 2022-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='user-profile/'),
        ),
    ]
