# Generated by Django 4.0.4 on 2022-06-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_account_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
    ]
