# Generated by Django 4.0.4 on 2022-06-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0011_reviewrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRating',
            new_name='ProductReview',
        ),
    ]
