# Generated by Django 4.0.4 on 2022-06-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_reviewrating_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
