# Generated by Django 4.0.4 on 2022-06-21 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='defualt_address',
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
