# Generated by Django 4.0.4 on 2022-06-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('category_description', models.TextField()),
                ('category_image', models.ImageField(blank=True, upload_to='image/category')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('image_1', models.ImageField(upload_to='image/product')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image/product')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image/product')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='image/product')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
