# Generated by Django 4.0.4 on 2022-06-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
