# Generated by Django 4.0.4 on 2022-06-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_delete_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
