# Generated by Django 4.0.4 on 2022-06-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('packed', 'packed'), ('shipped', 'shipped'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending', max_length=150),
        ),
    ]
