# Generated by Django 4.0.4 on 2022-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('shipped', 'shipped'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='ordered', max_length=150),
        ),
    ]
